// src/utils/exportUtils.js
import { utils, writeFile } from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';
import html2canvas from 'html2canvas';

// --- CSV EXPORT ---
export const exportToCsv = (data, columns, filters) => {
    const header = columns.map(c => c.Header).filter(h => h !== 'Actions' && h !== 'S.No.');
    const body = data.map(row => {
        const rowData = {};
        columns.forEach(col => {
            if (col.accessor && typeof col.accessor === 'string' && col.Header !== 'Actions' && col.Header !== 'S.No.') {
                rowData[col.Header] = row[col.accessor];
            }
        });
        return rowData;
    });

    const worksheet = utils.json_to_sheet(body, { header });
    const workbook = utils.book_new();
    utils.book_append_sheet(workbook, worksheet, 'Report');
    
    const filename = `PM_AJAY_Report_${new Date().toISOString().split('T')[0]}.xlsx`;
    writeFile(workbook, filename);
};

// --- PDF EXPORT ---
export const exportToPdf = async (data, columns, filters, includeCharts, chartContainerRef) => {
    const doc = new jsPDF({
        orientation: 'landscape',
        unit: 'px',
        format: 'a4'
    });

    // 1. Add Header and Metadata
    doc.setFontSize(18);
    doc.setTextColor('#0B57A4');
    doc.text('PM-AJAY Reports & Analytics', 40, 40);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 40, 55);
    doc.text(`Generated by: Admin User (Simulation)`, 40, 65);
    
    const filterText = `Active Filters: State: ${filters.state}, FY: ${filters.financialYear}, District: ${filters.district}`;
    doc.text(filterText, 40, 75);

    // 2. Add Charts (if included)
    if (includeCharts && chartContainerRef.current) {
        doc.addPage();
        doc.text('Charts & Visualizations', 40, 40);
        try {
            const canvas = await html2canvas(chartContainerRef.current, { scale: 2 });
            const imgData = canvas.toDataURL('image/png');
            // A4 landscape width is ~841px, height ~595px. We use px unit.
            const imgProps = doc.getImageProperties(imgData);
            const pdfWidth = doc.internal.pageSize.getWidth() - 80; // with margin
            const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
            doc.addImage(imgData, 'PNG', 40, 60, pdfWidth, pdfHeight);
        } catch (error) {
            console.error("Error generating chart image:", error);
            doc.text("Could not generate chart image.", 40, 60);
        }
    }
    
    // 3. Add Data Table
    doc.addPage();
    doc.text('Detailed Report Data', 40, 40);

    const tableColumns = columns.map(c => c.Header).filter(h => h !== 'Actions' && h !== 'S.No.');
    const tableRows = data.map((row, i) => {
        return [
            i + 1,
            row.proposalYear,
            row.state,
            row.district,
            row.projectsSubmitted,
            row.notionalAllocation,
            row.sanctionedProjects,
            row.sanctionedAmount
        ];
    });

    doc.autoTable({
        head: [['S.No.', ...tableColumns]],
        body: tableRows,
        startY: 50,
        headStyles: { fillColor: '#0B57A4' },
        styles: { fontSize: 8 },
        margin: { left: 40, right: 40 },
    });
    
    const filename = `PM_AJAY_Report_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(filename);
};
